# Generated by Django 4.0.2 on 2022-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='Receiver Name')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Info',
            },
        ),
    ]
